name: Go Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - app/**

concurrency:
  group: go-unit-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Go unit tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: app/go.mod
          cache-dependency-path: app/go.sum

      - name: Run tests
        run: go test ./...
